# Configuration for Cloudflare Pages

# Build settings
[build]
  command = "npm run build"
  publish = "dist"
  node_bundler = "esbuild"

# Environment variables
[env]
  NODE_VERSION = "18"

# Headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
